# Generated by Django 3.2.16 on 2023-03-21 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productmeta'),
        ('order', '0002_alter_order_sub_total'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=10, null=True)),
                ('store_keeping_unit', models.CharField(max_length=20, null=True)),
                ('mrp', models.DecimalField(decimal_places=4, max_digits=4, null=True)),
                ('discount', models.DecimalField(decimal_places=4, max_digits=4, null=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=4, null=True)),
                ('quantity', models.SmallIntegerField(max_length=10)),
                ('sold', models.SmallIntegerField(max_length=10)),
                ('available', models.SmallIntegerField(max_length=10)),
                ('defective', models.SmallIntegerField(max_length=10)),
                ('created_by', models.SmallIntegerField(max_length=5)),
                ('updated_by', models.SmallIntegerField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.brand')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
