# Generated by Django 3.2.16 on 2023-03-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
