# Generated by Django 3.2.16 on 2023-03-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_productmeta'),
        ('item', '0002_item'),
        ('order', '0002_alter_order_sub_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_keeping_unit', models.CharField(max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=4, null=True)),
                ('discount', models.DecimalField(decimal_places=4, max_digits=4, null=True)),
                ('quantity', models.SmallIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.TextField(max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
